### ISSUE TITLE
 module 'ssl' has no attribute 'PROTOCOL_SSLv3' ]

### ISSUE THREAD

**Issue by catroot** [veegee/guv#33]
```python
gunicorn test:hello  -b 0.0.0.0:8060 -w 2 -k guv.GuvWorker

Error: class uri 'guv.GuvWorker' invalid or not found:

[Traceback (most recent call last):
  File "/home/project0/venv/lib/python3.5/site-packages/gunicorn/util.py", line 142, in load_class
    mod = import_module('.'.join(components))
  File "/home/project0/venv/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/project0/venv/lib/python3.5/site-packages/guv/__init__.py", line 14, in <module>
    from .server import serve, listen, connect, StopServe, wrap_ssl
  File "/home/project0/venv/lib/python3.5/site-packages/guv/server.py", line 6, in <module>
    from .green import socket, ssl
  File "/home/project0/venv/lib/python3.5/site-packages/guv/green/ssl.py", line 5, in <module>
    from . import _ssl33 as _ssl3
  File "/home/project0/venv/lib/python3.5/site-packages/guv/green/_ssl33.py", line 26, in <module>
    PROTOCOL_SSLv3 = ssl_orig.PROTOCOL_SSLv3
AttributeError: module 'ssl' has no attribute 'PROTOCOL_SSLv3'
]
```
ubuntu 16.04 python 3.5.2

**Comment by catroot** [comment]
My suggestion is

`PROTOCOL_SSLv3 = ssl_orig.PROTOCOL_SSLv3 if hasattr(ssl_orig, "PROTOCOL_SSLv3") else None`
