### ISSUE TITLE
Problems running examples

### ISSUE THREAD

**Issue by icook** [veegee/guv#5]
I'm probably doing something silly, so sorry if this is just noise.

**Enviroment**
- Ubuntu 14.04
- Python 3.4.1-1+saucy1
- libuv-dev 0.10.22-2
- libffi-dev 3.1~rc1+r3.0.13-12

**Steps Taken**
1. Cloned master
2. New Python 3.4 virtualenv
3. `pip install -e .`
4. `python examples/crawler.py`

**Problem**

```
examples/pyuv_cffi/__pycache__/_cffi__x735818ex4ef4bffa.c: In function ‘_cffi_f_uv_has_ref’:
examples/pyuv_cffi/__pycache__/_cffi__x735818ex4ef4bffa.c:368:3: warning: implicit declaration of function ‘uv_has_ref’ [-Wimplicit-function-declaration]
   { result = uv_has_ref(x0); }
   ^
examples/pyuv_cffi/__pycache__/_cffi__x735818ex4ef4bffa.c: In function ‘_cffi_f_uv_idle_start’:
examples/pyuv_cffi/__pycache__/_cffi__x735818ex4ef4bffa.c:449:3: warning: passing argument 2 of ‘uv_idle_start’ from incompatible pointer type [enabled by default]
   { result = uv_idle_start(x0, x1); }
   ^
In file included from examples/pyuv_cffi/__pycache__/_cffi__x735818ex4ef4bffa.c:190:0:
/usr/include/uv.h:1167:15: note: expected ‘uv_idle_cb’ but argument is of type ‘void (*)(struct uv_idle_t *)’
 UV_EXTERN int uv_idle_start(uv_idle_t* idle, uv_idle_cb cb);
               ^
examples/pyuv_cffi/__pycache__/_cffi__x735818ex4ef4bffa.c: In function ‘_cffi_f_uv_loop_alive’:
examples/pyuv_cffi/__pycache__/_cffi__x735818ex4ef4bffa.c:557:3: warning: implicit declaration of function ‘uv_loop_alive’ [-Wimplicit-function-declaration]
   { result = uv_loop_alive(x0); }
   ^
examples/pyuv_cffi/__pycache__/_cffi__x735818ex4ef4bffa.c: In function ‘_cffi_f_uv_loop_init’:
examples/pyuv_cffi/__pycache__/_cffi__x735818ex4ef4bffa.c:584:3: warning: implicit declaration of function ‘uv_loop_init’ [-Wimplicit-function-declaration]
   { result = uv_loop_init(x0); }
   ^
examples/pyuv_cffi/__pycache__/_cffi__x735818ex4ef4bffa.c: In function ‘_cffi_f_uv_prepare_start’:
examples/pyuv_cffi/__pycache__/_cffi__x735818ex4ef4bffa.c:785:3: warning: passing argument 2 of ‘uv_prepare_start’ from incompatible pointer type [enabled by default]
   { result = uv_prepare_start(x0, x1); }
   ^
In file included from examples/pyuv_cffi/__pycache__/_cffi__x735818ex4ef4bffa.c:190:0:
/usr/include/uv.h:1129:15: note: expected ‘uv_prepare_cb’ but argument is of type ‘void (*)(struct uv_prepare_t *)’
 UV_EXTERN int uv_prepare_start(uv_prepare_t* prepare, uv_prepare_cb cb);
               ^
examples/pyuv_cffi/__pycache__/_cffi__x735818ex4ef4bffa.c: In function ‘_cffi_f_uv_timer_start’:
examples/pyuv_cffi/__pycache__/_cffi__x735818ex4ef4bffa.c:1200:3: warning: passing argument 2 of ‘uv_timer_start’ from incompatible pointer type [enabled by default]
   { result = uv_timer_start(x0, x1, x2, x3); }
   ^
In file included from examples/pyuv_cffi/__pycache__/_cffi__x735818ex4ef4bffa.c:190:0:
/usr/include/uv.h:1217:15: note: expected ‘uv_timer_cb’ but argument is of type ‘void (*)(struct uv_timer_t *)’
 UV_EXTERN int uv_timer_start(uv_timer_t* handle,
               ^
Traceback (most recent call last):
  File "/home/isaac2/.virtualenvs/guv/lib/python3.4/site-packages/cffi/vengine_cpy.py", line 146, in load_library
    self.verifier.modulefilename)
ImportError: /home/isaac2/programming/guv/examples/pyuv_cffi/__pycache__/_cffi__x735818ex4ef4bffa.cpython-34m-x86_64-linux-gnu.so: undefined symbol: uv_loop_init

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "examples/crawler.py", line 1, in <module>
    import guv
  File "/home/isaac2/programming/guv/examples/guv/__init__.py", line 14, in <module>
    import pyuv_cffi  # only to compile the shared library before monkey-patching
  File "/home/isaac2/programming/guv/examples/pyuv_cffi/__init__.py", line 25, in <module>
    libuv = ffi.verify(f.read(), libraries=['uv'])
  File "/home/isaac2/.virtualenvs/guv/lib/python3.4/site-packages/cffi/api.py", line 340, in verify
    lib = self.verifier.load_library()
  File "/home/isaac2/.virtualenvs/guv/lib/python3.4/site-packages/cffi/verifier.py", line 75, in load_library
    return self._load_library()
  File "/home/isaac2/.virtualenvs/guv/lib/python3.4/site-packages/cffi/verifier.py", line 151, in _load_library
    return self._vengine.load_library()
  File "/home/isaac2/.virtualenvs/guv/lib/python3.4/site-packages/cffi/vengine_cpy.py", line 149, in load_library
    raise ffiplatform.VerificationError(error)
cffi.ffiplatform.VerificationError: importing '/home/isaac2/programming/guv/examples/pyuv_cffi/__pycache__/_cffi__x735818ex4ef4bffa.cpython-34m-x86_64-linux-gnu.so': /home/isaac2/programming/guv/examples/pyuv_cffi/__pycache__/_cffi__x735818ex4ef4bffa.cpython-34m-x86_64-linux-gnu.so: undefined symbol: uv_loop_init
```

Perhaps I've installed the wrong dependencies? I had hiccups at first that I got past by installing `libuv-dev` and `libffi-dev`.

**Comment by aidos** [comment]
Now I'm the one feeling like the noob. I installed libuv (built from http://libuv.org/dist/v1.4.2/) but when I try to import guv I run into the following:

```
ImportError: libuv.so.1: cannot open shared object file: No such file or directory
```

I'm assuming something is messed up / missing in my paths somewhere? My python in running from an environment built using pyvenv-3.4.

Just trying to rebuild the latest version of libuv from the code on gituhub to see if that helps.

**Comment by veegee** [comment]
Try `sudo ldconfig` after your libuv install step.

**Comment by aidos** [comment]
Boom, that's done it! (Suddenly wondering how many times that would have saved other hassles in my life)

I was quietly installing gevent in a python2 env in case I couldn't get this working. Ctrl-C!

Thanks
